language: php
php:
  - "5.3"
before_script:
  - git clone git://github.com/vivid-planet/library.git
script: "php bootstrap.php test --exclude-group=slow"
notificaitons:
  irc: "irc.freenode.org#kwf"

