language: php
php:
  - "5.3"
before_script:
  - git clone git://github.com/vivid-planet/library.git
  - pwd
  - ls -l
  - php --info
  - echo "library/zend/%version%" > include_path
  - ls library/zend
  - php bootstrap.php
script: "php bootstrap.php test --exclude-group=slow"
notificaitons:
  irc: "irc.freenode.org#kwf"

