parameters:
    fos_rest.view_handler.default.class: KwfBundle\Rest\ViewHandler

services:
    kwf.session.storage:
        class: KwfBundle\HttpFoundation\Session\KwfSessionStorage
        public: false

    kwf.rest.apidoc.extractor:
        class: KwfBundle\Rest\ApiDocExtractor
        tags:
            - { name: nelmio_api_doc.extractor.handler }
        public: false

    kwf_authenticator:
        class:  KwfBundle\Security\KwfUserAuthenticator
        public: false

    kwf_user_provider:
        class: KwfBundle\Security\KwfUserProvider

    kwf.security.entrypoint.api:
        class: KwfBundle\Security\EntryPoint

    kwf_model_normalizer:
        class: KwfBundle\Serializer\KwfModelNormalizer
        arguments: ['@serializer.mapping.class_metadata_factory']
        tags:
            - { name: serializer.normalizer }
        public: false
